name: 编译mipsel-2.8.x

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: 克隆源码
        shell: bash
        run: |
          git clone https://github.com/lmq8267/n2n-2.8.x /opt/n2n
          rm -rf /opt/n2n/thirdparty/liblfds711
          git clone https://github.com/bin/liblfds_711.git /opt/n2n/thirdparty/liblfds711
          #下载编译工具链
          wget -c https://github.com/lmq8267/n2n-2.8.x/releases/download/toolchain/host.zip -P /opt/gcc/
          unzip /opt/gcc/host.zip -d /opt/gcc/
          sudo chmod 777 -R /opt/gcc
      - 
        name: 编译n2n
        shell: bash
        run: |
          cd /opt/n2n
          export PATH=$PATH:/opt/gcc/host/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/host/lib
          mipsel-linux-gcc -v
          #编译静态程序
          sed -i 's|-Wshadow|-Wshadow -static |g' ./CMakeLists.txt
          #设置编译平台
          sed -i '/# N2n release information/i set(CMAKE_SYSTEM_NAME Linux)' ./CMakeLists.txt
          sed -i '/# N2n release information/i set(CMAKE_SYSTEM_PROCESSOR mipsel)' ./CMakeLists.txt
          #设置编译gcc
          sed -i '/# N2n release information/i set(CMAKE_C_COMPILER mipsel-linux-gcc)' ./CMakeLists.txt
          sed -i '/# N2n release information/i set(CMAKE_CXX_COMPILER mipsel-linux-g++)' ./CMakeLists.txt
          #设置编译静态程序
          sed -i '/# N2n release information/i set(CMAKE_CXX_FLAGS "${CMAKE_CXX_LINKER_FLAGS} -static")' ./CMakeLists.txt
          sed -i '/# N2n release information/i set(CMAKE_CXE_LINKER_FLAGS "${CMAKE_CEXE_LINKER_FLAGS} -static")' ./CMakeLists.txt
          #开始编译
          cmake . .
          make
        continue-on-error: true
      - 
        name: 剥离压缩
        run: |
          mkdir -p /opt/n2n-v.2.8.x-pthread_mipsel/upx
          #下载upx压缩工具
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          cd /opt/n2n
          #查看当前目录文件
          ls -la
          #查看edge二进制文件信息
          file edge
          cp -rf /opt/n2n/edge /opt/n2n-v.2.8.x-pthread_mipsel/edge
          cp -rf /opt/n2n/example_edge_embed /opt/n2n-v.2.8.x-pthread_mipsel/example_edge_embed
          cp -rf /opt/n2n/example_edge_embed_quick_edge_init /opt/n2n-v.2.8.x-pthread_mipsel/example_edge_embed_quick_edge_init
          cp -rf /opt/n2n/example_sn_embed /opt/n2n-v.2.8.x-pthread_mipsel/example_sn_embed
          cp -rf /opt/n2n/supernode /opt/n2n-v.2.8.x-pthread_mipsel/supernode
          cp -rf n2n-benchmark /opt/n2n-v.2.8.x-pthread_mipsel/n2n-benchmark
          
          cp -rf /opt/n2n/edge /opt/n2n-v.2.8.x-pthread_mipsel/upx/edge
          cp -rf /opt/n2n/example_edge_embed /opt/n2n-v.2.8.x-pthread_mipsel/upx/example_edge_embed
          cp -rf /opt/n2n/example_edge_embed_quick_edge_init /opt/n2n-v.2.8.x-pthread_mipsel/upx/example_edge_embed_quick_edge_init
          cp -rf /opt/n2n/example_sn_embed /opt/n2n-v.2.8.x-pthread_mipsel/upx/example_sn_embed
          cp -rf /opt/n2n/supernode /opt/n2n-v.2.8.x-pthread_mipsel/upx/supernode
          cp -rf n2n-benchmark /opt/n2n-v.2.8.x-pthread_mipsel/upx/n2n-benchmark
          
          cd /opt/n2n-v.2.8.x-pthread_mipsel/upx
          #剥离
          /opt/gcc/host/bin/mipsel-linux-strip edge
          /opt/gcc/host/bin/mipsel-linux-strip example_edge_embed
          /opt/gcc/host/bin/mipsel-linux-strip example_edge_embed_quick_edge_init
          /opt/gcc/host/bin/mipsel-linux-strip example_sn_embed
          /opt/gcc/host/bin/mipsel-linux-strip supernode
          /opt/gcc/host/bin/mipsel-linux-strip n2n-benchmark
          #压缩
          /opt/upx-3.95-amd64_linux/upx edge
          /opt/upx-3.95-amd64_linux/upx example_edge_embed
          /opt/upx-3.95-amd64_linux/upx example_edge_embed_quick_edge_init
          /opt/upx-3.95-amd64_linux/upx example_sn_embed
          /opt/upx-3.95-amd64_linux/upx supernode
          /opt/upx-3.95-amd64_linux/upx n2n-benchmark
          cd /opt
          tagtime=$(date '+%Y-%m-%d')
          echo "tagtime=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          #打包
          zip -r n2n-v.2.8.x-pthread_mipsel-${tagtime}.zip n2n-v.2.8.x-pthread_mipsel
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: n2n
         path: /opt/n2n-v.2.8.x-pthread_mipsel-${{ env.tagtime }}.zip
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           zip压缩包里有所有的程序（原版 压缩版）
           
          tag_name: ${{ env.tagtime }}
          files: |
              /opt/n2n-v.2.8.x-pthread_mipsel-${{ env.tagtime }}.zip
              /opt/n2n-v.2.8.x-pthread_mipsel/upx/edge
              /opt/n2n-v.2.8.x-pthread_mipsel/upx/supernode
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0 
